//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chinook.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InvoiceResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InvoiceResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chinook.Data.Resources.InvoiceResources", typeof(InvoiceResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices.
        /// </summary>
        public static string EntityPlural {
            get {
                return ResourceManager.GetString("EntityPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string EntitySingular {
            get {
                return ResourceManager.GetString("EntitySingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address.
        /// </summary>
        public static string PropertyBillingAddress {
            get {
                return ResourceManager.GetString("PropertyBillingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing City.
        /// </summary>
        public static string PropertyBillingCity {
            get {
                return ResourceManager.GetString("PropertyBillingCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Country.
        /// </summary>
        public static string PropertyBillingCountry {
            get {
                return ResourceManager.GetString("PropertyBillingCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Postal Code.
        /// </summary>
        public static string PropertyBillingPostalCode {
            get {
                return ResourceManager.GetString("PropertyBillingPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing State.
        /// </summary>
        public static string PropertyBillingState {
            get {
                return ResourceManager.GetString("PropertyBillingState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Id.
        /// </summary>
        public static string PropertyCustomerId {
            get {
                return ResourceManager.GetString("PropertyCustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Date.
        /// </summary>
        public static string PropertyInvoiceDate {
            get {
                return ResourceManager.GetString("PropertyInvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Id.
        /// </summary>
        public static string PropertyInvoiceId {
            get {
                return ResourceManager.GetString("PropertyInvoiceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string PropertyTotal {
            get {
                return ResourceManager.GetString("PropertyTotal", resourceCulture);
            }
        }
    }
}
