//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chinook.WebServiceClient.ChinookServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChinookServiceReference.ChinookWebServiceSoap")]
    public interface ChinookWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        // CODEGEN: Generating message contract since message SelectGenresRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectGenres", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ZDTOBase))]
        Chinook.WebServiceClient.ChinookServiceReference.SelectGenresResponse SelectGenres(Chinook.WebServiceClient.ChinookServiceReference.SelectGenresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectGenres", ReplyAction="*")]
        System.Threading.Tasks.Task<Chinook.WebServiceClient.ChinookServiceReference.SelectGenresResponse> SelectGenresAsync(Chinook.WebServiceClient.ChinookServiceReference.SelectGenresRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticationHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenreDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ZDTOBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GenreDTO : ZDTOBase {
        
        private int genreIdField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int GenreId {
            get {
                return this.genreIdField;
            }
            set {
                this.genreIdField = value;
                this.RaisePropertyChanged("GenreId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectGenres", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectGenresRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Chinook.WebServiceClient.ChinookServiceReference.AuthenticationHeader AuthenticationHeader;
        
        public SelectGenresRequest() {
        }
        
        public SelectGenresRequest(Chinook.WebServiceClient.ChinookServiceReference.AuthenticationHeader AuthenticationHeader) {
            this.AuthenticationHeader = AuthenticationHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectGenresResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectGenresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Chinook.WebServiceClient.ChinookServiceReference.GenreDTO[] SelectGenresResult;
        
        public SelectGenresResponse() {
        }
        
        public SelectGenresResponse(Chinook.WebServiceClient.ChinookServiceReference.GenreDTO[] SelectGenresResult) {
            this.SelectGenresResult = SelectGenresResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ChinookWebServiceSoapChannel : Chinook.WebServiceClient.ChinookServiceReference.ChinookWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChinookWebServiceSoapClient : System.ServiceModel.ClientBase<Chinook.WebServiceClient.ChinookServiceReference.ChinookWebServiceSoap>, Chinook.WebServiceClient.ChinookServiceReference.ChinookWebServiceSoap {
        
        public ChinookWebServiceSoapClient() {
        }
        
        public ChinookWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChinookWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChinookWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChinookWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chinook.WebServiceClient.ChinookServiceReference.SelectGenresResponse Chinook.WebServiceClient.ChinookServiceReference.ChinookWebServiceSoap.SelectGenres(Chinook.WebServiceClient.ChinookServiceReference.SelectGenresRequest request) {
            return base.Channel.SelectGenres(request);
        }
        
        public Chinook.WebServiceClient.ChinookServiceReference.GenreDTO[] SelectGenres(Chinook.WebServiceClient.ChinookServiceReference.AuthenticationHeader AuthenticationHeader) {
            Chinook.WebServiceClient.ChinookServiceReference.SelectGenresRequest inValue = new Chinook.WebServiceClient.ChinookServiceReference.SelectGenresRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            Chinook.WebServiceClient.ChinookServiceReference.SelectGenresResponse retVal = ((Chinook.WebServiceClient.ChinookServiceReference.ChinookWebServiceSoap)(this)).SelectGenres(inValue);
            return retVal.SelectGenresResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Chinook.WebServiceClient.ChinookServiceReference.SelectGenresResponse> Chinook.WebServiceClient.ChinookServiceReference.ChinookWebServiceSoap.SelectGenresAsync(Chinook.WebServiceClient.ChinookServiceReference.SelectGenresRequest request) {
            return base.Channel.SelectGenresAsync(request);
        }
        
        public System.Threading.Tasks.Task<Chinook.WebServiceClient.ChinookServiceReference.SelectGenresResponse> SelectGenresAsync(Chinook.WebServiceClient.ChinookServiceReference.AuthenticationHeader AuthenticationHeader) {
            Chinook.WebServiceClient.ChinookServiceReference.SelectGenresRequest inValue = new Chinook.WebServiceClient.ChinookServiceReference.SelectGenresRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            return ((Chinook.WebServiceClient.ChinookServiceReference.ChinookWebServiceSoap)(this)).SelectGenresAsync(inValue);
        }
    }
}
